### ISSUE TITLE
What are the ideas behind Tweener.TweenTo() "target" and "expression" parameters?

### ISSUE THREAD

**Issue by Dante3085** [craftworkgames/MonoGame.Extended-samples#2]
Tweener.TweenTo() has the following signature 
```
public Tween<TMember> TweenTo<TTarget, TMember>(TTarget target, Expression<Func<TTarget, TMember>> expression, TMember toValue, float duration, float delay = 0f)
            where TTarget : class
            where TMember : struct
```
I can't quite wrap my head around the parameters **target** and **expression**. Do they represent the mechanism through which the Tweener gets the value that it needs to tween? So **target** contains a member of type TMember which is accessed as **expression** describes?

**Comment by lithiumtoast** [comment]
`TTarget` is a class type and `TMember` is a member of the class which is a struct such as a field.

See https://github.com/craftworkgames/MonoGame.Extended-samples/blob/master/src/Demos/Tweening/MainGame.cs
