### ISSUE TITLE
Platformer player animations not working

### ISSUE THREAD

**Issue by Potter002** [craftworkgames/MonoGame.Extended-samples#22]
Hi,
I had a problem while trying to tests MonoGame Extended according to example codes and animation sprite didn't work for me, so I've decided to try the sample code (I've assumed earlier that it works) and animation for player is not working for some reason.
At  the same time animations for blue guy works fine.

**Comment by kaltinril** [comment]
@Potter002  please provide more details, which sample does not work?

I am able to run Both projects under 2DAnimations:
1. AnimiatedSpriteSample
2. SpriteSheetSample

**Comment by Potter002** [comment]
Hi, the problem is with Platformer Game, player animation doesn't. It displays only 1 static image(first sprite from SpriteSheet) no matter of the action.
