### ISSUE TITLE
Content pipeline version mismatch between csproj and Content.mgcb files

### ISSUE THREAD

**Issue by AnotherEpigone** [craftworkgames/MonoGame.Extended-samples#3]
On a new clone and build, I get about 35 "Failed to create importer" errors.

I noticed that all the Content.mgcb files reference this package:
"/reference:..\..\..\..\.nuget\packages\monogame.extended.content.pipeline\3.9.0-alpha0001\tools\MonoGame.Extended.Content.Pipeline.dll"

Whereas the actual projects reference the latest stable version 3.8.0, not 3.9.0-alpha0001.

Fixing that path fixes the build for me.

**Comment by lithiumtoast** [comment]
OK; yes, this was my mistake.
