### ISSUE TITLE
Pipeline Failing to Convert tmx File

### ISSUE THREAD

**Issue by StockBrick** [craftworkgames/MonoGame.Extended-samples#5]
Hi

I've added a NuGet.config file and changed the reference to point to the dll files in the Nuget packages folder but the tmx file still fails to build in the MGCB editor with the attached error message:
![image](https://user-images.githubusercontent.com/37738664/103703840-32c40180-4fa0-11eb-8c25-ea0ec89a9dc0.png)

Am I doing something wrong? I'm no expert.

I don't understand why the error message refers to a rpgTiles.png file which doesn't match the name of my tmx file.

Many thanks

Stephen

**Comment by DimitarBogdanov** [comment]
Hey, is your tmx map having the tileset stored somewhere else, outside of it? (e.g. that second location)

**Comment by AristurtleDev** [comment]
This is not an issue related to the samples, please reopen issue in main MonoGame.Extended repository if still having issue.
